version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "11:00"
    assignees: 
    - luke-h1
    rebase-strategy: "auto"
