trigger:
pr: [ 'dev' ]

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm i --legacy-peer-deps
  displayName: 'Install dependencies'


- script: npm run lint
  displayName: 'run eslint'

- script: npm run test
  displayName: 'run all unit tests'