import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: {
    [process.env.HYGRAPH_URL as string]: {
      headers: {},
    },
  },
  documents: ['./src/**/graphql/**/*.graphql'],
  hooks: {
    afterAllFileWrite: ['prettier --write'],
  },
  generates: {
    './src/graphql/generated/index.tsx': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-query',
        {
          add: {
            content: `
            /* eslint-disable */
            // @ts-ignore
            // DO NOT EDIT
            // This file is automatically generated, run pnpm gen to update
            `,
          },
        },
      ],
    },
  },
};

export default config;
