import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      [process.env.HYGRAPH_URL as string]: {
        // headers: { Authorization: `Bearer ${process.env.CMS_PROD_TOKEN}` },
      },
    },
  ],
  documents: ['src/graphql/**/*.gql', '!node_modules'],
  hooks: {
    afterAllFileWrite: 'prettier --write',
  },
  generates: {
    'src/graphql/generated/generated.ts': {
      plugins: [
        {
          add: {
            content: `
            /* eslint-disable */
            // DO NOT EDIT
            // This file is automatically generated, run pnpm gen to update
        `,
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-urql',
      ],
    },
    './schema.generated.graphql': {
      plugins: ['schema-ast'],
    },
  },
};
export default config;
