name = "lhowsam-production"
workers_dev = false
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "prod.lhowsam.com", custom_domain = true }
]


[env.staging]

name = "lhowsam-staging"
workers_dev = false
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "staging.lhowsam.com", custom_domain = true }
]
