name: Deploy
description: Deploy frontend to Vercel
inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  vercel-org-id:
    description: 'Vercel organization ID'
    required: true
  vercel-project-id:
    description: 'Vercel project ID'
    required: true
  environment:
    description: 'environment to deploy to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get current date
      id: date
      run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get git sha
      id: git-sha
      run: echo "git-sha=${{ github.sha }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set vercel environment variables
      shell: bash
      run: |
        # DEPLOYED_AT
        pnpm vc env rm DEPLOYED_AT production --token ${VERCEL_TOKEN} --yes
        echo ${{ steps.date.outputs.date }} | pnpm vc env add DEPLOYED_AT production --token ${VERCEL_TOKEN}

        # DEPLOYED_BY
        pnpm vc env rm DEPLOYED_BY production --token ${VERCEL_TOKEN} --yes
        echo ${{ github.actor }} | pnpm vc env add DEPLOYED_BY production --token ${VERCEL_TOKEN}

        # GIT_SHA
        pnpm vc env rm GIT_SHA production --token ${VERCEL_TOKEN} --yes
        echo ${{ steps.git-sha.outputs.git-sha }} | pnpm vc env add GIT_SHA production --token ${VERCEL_TOKEN}
      env:
        VERCEL_TOKEN: ${{ inputs.vercel-token }}
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}

    - name: Deploy to ${{ inputs.environment }}
      run: pnpm vc -f --prod --token ${{ inputs.vercel-token }}
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.vercel-token }}
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}

    - name: ${{ inputs.environment }} UI tests
      run: make e2e-${{ inputs.environment }}
      shell: bash
