"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.BlogLink = exports.BlogSection = exports.BlogHeader = exports.BlogArticle = exports.BlogList = exports.BlogFlex = exports.BlogIntro = exports.BlogContainer = void 0;
/* eslint-disable */
var gatsby_1 = require("gatsby");
var styled_components_1 = require("styled-components");
exports.BlogContainer = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  justify-content: left;\n  align-items: left;\n  padding-left: 1.5rem;\n\n  background: ", ";\n  min-height: 65vh;\n  h1 { \n\n    font-size: clamp(1rem, 8vw, 2.7rem);\n    color: ", ";\n    text-align: left;\n    font-weight: 700;\n  }\n"], ["\n  display: flex;\n  flex-direction: column;\n  justify-content: left;\n  align-items: left;\n  padding-left: 1.5rem;\n\n  background: ", ";\n  min-height: 65vh;\n  h1 { \n\n    font-size: clamp(1rem, 8vw, 2.7rem);\n    color: ", ";\n    text-align: left;\n    font-weight: 700;\n  }\n"])), function (props) { return props.theme.BlueBackgroundColor; }, function (props) { return props.theme.lightTextColor; });
exports.BlogIntro = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  justify-content: left;\n  align-items: left;\n  margin-top: 10rem;\n"], ["\n  display: flex;\n  flex-direction: column;\n  justify-content: left;\n  align-items: left;\n  margin-top: 10rem;\n"])));
exports.BlogFlex = styled_components_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  min-width: 50vh;\n  background: ", ";\n  padding-left: 1.5rem;\n\n\n"], ["\n  min-width: 50vh;\n  background: ", ";\n  padding-left: 1.5rem;\n\n\n"])), function (props) { return props.theme.primaryBackgroundColor; });
exports.BlogList = styled_components_1["default"].li(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  padding-left: 0;\n  color: ", ";\n  list-style-type: none;\n  margin-bottom: calc((2rem) / 2 ); \n  p { \n    margin-bottom: calc((2rem) / 2); \n    color: ", ";\n\n  }\n  *:last-child { \n    margin-bottom: 0;\n  }\n  > ul  {\n    margin-left: 2rem; \n    margin-top: calc((2rem) / 2); \n    color: ", ";\n\n  }\n"], ["\n  padding-left: 0;\n  color: ", ";\n  list-style-type: none;\n  margin-bottom: calc((2rem) / 2 ); \n  p { \n    margin-bottom: calc((2rem) / 2); \n    color: ", ";\n\n  }\n  *:last-child { \n    margin-bottom: 0;\n  }\n  > ul  {\n    margin-left: 2rem; \n    margin-top: calc((2rem) / 2); \n    color: ", ";\n\n  }\n"])), function (props) { return props.theme.textColor; }, function (props) { return props.theme.textColor; }, function (props) { return props.theme.textColor; });
exports.BlogArticle = styled_components_1["default"].article(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  margin-bottom: 2rem;\n  margin-top: 2rem;\n  p { \n    margin-bottom: 0;\n    color: ", ";\n\n  }\n  h2 {\n    margin-bottom: 2rem;\n    color: ", ";\n\n    margin-top: 0;\n  }\n"], ["\n  margin-bottom: 2rem;\n  margin-top: 2rem;\n  p { \n    margin-bottom: 0;\n    color: ", ";\n\n  }\n  h2 {\n    margin-bottom: 2rem;\n    color: ", ";\n\n    margin-top: 0;\n  }\n"])), function (props) { return props.theme.textColor; }, function (props) { return props.theme.textColor; });
exports.BlogHeader = styled_components_1["default"].header(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  margin-bottom: 1rem;\n  color: ", ";\n\n"], ["\n  margin-bottom: 1rem;\n  color: ", ";\n\n"])), function (props) { return props.theme.primaryColor; });
exports.BlogSection = styled_components_1["default"].section(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\np { \n  width: 70%;\n}\n"], ["\np { \n  width: 70%;\n}\n"])));
exports.BlogLink = styled_components_1["default"](gatsby_1.Link)(templateObject_8 || (templateObject_8 = __makeTemplateObject([""], [""])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8;
