name: UI tests
description: Run UI tests
inputs:
  target:
    description: 'make target to execute'
    required: true
runs:
  using: composite
  steps:
    - name: Install browsers
      run: pnpx playwright install --with-deps
      shell: bash

    - name: UI tests
      if: ${{ inputs.target == 'e2e-local' }}
      run: pnpx start-server-and-test start 3000 uitest:local
      shell: bash

    - name: UI tests
      if: ${{ inputs.target != 'e2e-local' }}
      run: make ${{ inputs.target }}
      shell: bash
