name: Deploy AWS
description: Deploy frontend to AWS
inputs:
  aws-key-id:
    description: 'AWS access key'
    required: true
  aws-secret-access-key:
    description: 'AWS secret key'
    required: true
  environment:
    description: 'environment to deploy to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate environment
      shell: bash
      run: if [ "${{ inputs.environment }}" != "test" ]; then echo "Invalid environment"; exit 1; fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-2
        mask-aws-account-id: true

    - name: build
      shell: bash
      run: pnpm run build:open-next

    - name: Terraform init
      shell: bash
      working-directory: terraform
      run: |
        terraform init -backend-config="key=vpc/${{ inputs.environment }}.tfstate" -backend-config="bucket=lhowsam-web-${{ inputs.environment }}-terraform-state" -input=false

    - name: Deploy DynamoDB lock table if not exists
      shell: bash
      working-directory: terraform
      run: terraform apply -auto-approve -target=aws_dynamodb_table.dynamodb_terraform_lock

    - name: Terraform fmt -check
      shell: bash
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform validate
      shell: bash
      working-directory: terraform
      run: terraform validate

    - name: Terraform plan
      id: plan
      shell: bash
      working-directory: terraform
      run: terraform plan -no-color -out=tfplan

    - name: Terraform apply
      shell: bash
      working-directory: terraform
      run: terraform apply -auto-approve tfplan
