name: Build
on:
  pull_request:
    branches: [dev, main]
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}        
    name: Build 
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
          SENTRY_ORG: op://ci-cd/lhowsam-dev/SENTRY_ORG
          SENTRY_PROJECT: op://ci-cd/lhowsam-dev/SENTRY_PROJECT
          SENTRY_AUTH_TOKEN: op://ci-cd/lhowsam-dev/SENTRY_AUTH_TOKEN
          PUBLIC_SENTRY_DSN: op://ci-cd/lhowsam-dev/PUBLIC_SENTRY_DSN
          PUBLIC_URL: op://ci-cd/lhowsam-dev/PUBLIC_URL

      - name: install
        uses: ./.github/actions/install

      - name: Build frontend
        uses: ./.github/actions/build
