name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'dev'
        type: string

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  deploy-live:
    runs-on: ubuntu-latest
    name: Deploy to live
    concurrency:
      group: deploy-live-${{ inputs.branch }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
          PUBLIC_URL: op://ci-cd/lhowsam-prod/PUBLIC_URL
          VERCEL_PROJECT_ID: op://ci-cd/lhowsam-prod/VERCEL_PROJECT_ID
          VERCEL_TOKEN: op://ci-cd/lhowsam-prod/VERCEL_TOKEN
          VERCEL_ORG_ID: op://ci-cd/lhowsam-prod/VERCEL_ORG_ID
          SENTRY_ORG: op://ci-cd/lhowsam-prod/SENTRY_ORG
          SENTRY_PROJECT: op://ci-cd/lhowsam-prod/SENTRY_PROJECT
          SENTRY_AUTH_TOKEN: op://ci-cd/lhowsam-prod/SENTRY_AUTH_TOKEN
          PUBLIC_SENTRY_DSN: op://ci-cd/lhowsam-prod/PUBLIC_SENTRY_DSN

      - name: install
        uses: ./.github/actions/install

      - name: Build
        uses: ./.github/actions/build
      
      - name: Deploy to live
        uses: ./.github/actions/deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          environment: prod

      - name: prod UI tests
        run: bun run e2e:prod
        shell: bash
