name: Deploy to Dev
on:
  push:
    branches:
      - dev
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy to dev
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
          PUBLIC_URL: op://ci-cd/lhowsam-dev/PUBLIC_URL
          VERCEL_PROJECT_ID: op://ci-cd/lhowsam-dev/VERCEL_PROJECT_ID
          VERCEL_TOKEN: op://ci-cd/lhowsam-dev/VERCEL_TOKEN
          VERCEL_ORG_ID: op://ci-cd/lhowsam-dev/VERCEL_ORG_ID
          SENTRY_ORG: op://ci-cd/lhowsam-dev/SENTRY_ORG
          SENTRY_PROJECT: op://ci-cd/lhowsam-dev/SENTRY_PROJECT
          SENTRY_AUTH_TOKEN: op://ci-cd/lhowsam-dev/SENTRY_AUTH_TOKEN
          PUBLIC_SENTRY_DSN: op://ci-cd/lhowsam-dev/PUBLIC_SENTRY_DSN

      - name: install
        uses: ./.github/actions/install

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy to dev
        uses: ./.github/actions/deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          environment: dev
