name: CI / deploy dev
on:
  push:
    branches: [dev]
env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  VERCEL_DEV_DEPLOY_HOOK: ${{ secrets.VERCEL_DEV_DEPLOY_HOOK }}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 16 
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies
        run: yarn

      - name: format
        run: yarn format

      - name: lint
        run: yarn lint

      - name: jest
        run: yarn test

      - name: tsc
        run: yarn tsc

      - name: build
        run: yarn build

      - name: deploy dev
        run: curl -X POST ${{ secrets.VERCEL_DEV_DEPLOY_HOOK }}
