name: UI tests (dev)
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 22 * * *'
env: 
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  test:
    name: e2e dev
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
          PUBLIC_URL: op://ci-cd/lhowsam-dev/PUBLIC_URL
          BASIC_AUTH_USER: op://ci-cd/lhowsam-dev/BASIC_AUTH_USER
          BASIC_AUTH_PASSWORD: op://ci-cd/lhowsam-dev/BASIC_AUTH_PASSWORD
          SENTRY_ORG: op://ci-cd/lhowsam-dev/SENTRY_ORG
          SENTRY_PROJECT: op://ci-cd/lhowsam-dev/SENTRY_PROJECT
          SENTRY_AUTH_TOKEN: op://ci-cd/lhowsam-dev/SENTRY_AUTH_TOKEN
          PUBLIC_SENTRY_DSN: op://ci-cd/lhowsam-dev/PUBLIC_SENTRY_DSN
      
      - name: install dependencies
        uses: ./.github/actions/install

      - name: UI tests dev
        uses: ./.github/actions/ui-test
        with:
          target: e2e:dev
