name: lighthouse
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci && npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: lhci autorun
