name: Lighthouse auditor 
on:
  push:
    branches:
      - dev
jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v3
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: './lighthouserc.json'