name: UI tests (live)
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 */12 * * *'
env: 
  NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  PNPM_VERSION: 9.4.0
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

jobs:
  test:
    name: e2e live
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      
      - name: install dependencies
        uses: ./.github/actions/install

      # - name: UI tests prod
      #   uses: ./.github/actions/ui-test
      #   with:
      #     target: e2e-prod
      - name: throw an error
        run: exit 1

  discord-fail-message:
    runs-on: ubuntu-latest
    if: failure()
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: apps/lambda

      - name: Discord fail notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_LIVE_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: '🚨 (testing workflow only) - Live UI tests lhowsam.com failed! 🚨 View test report -> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
