name: CI / Nightly tests (UI & unit)
on: 
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: luke-h1/checkout@v2.3.4

    - name: npm ci
      run: npm ci 

    - name: Jest unit tests
      run: npm run test:ci

    - name: Cypress UI tests 
      run: npm run cy:ci 