name: CI / Nightly tests 
on: 
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: luke-h1/checkout@v2.3.4
    - name: Install modules
      run: npm i 

    # - name: Run jest unit tests
    #   run: npm run test

    - name: Run UI tests 
      run: npm run cy:ci 