
   
name: CI / Nightly UI tests
on: 
  schedule:
    - cron: '0 22 * * *'
env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 16   

      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest
        
      - name: Install dependencies 
        run: yarn

      - name: Cypress run (prod)
        uses: luke-h1/github-action@v2
        with:
          config: baseUrl=https://lhowsam.com
          test: yarn cy:prod
          working-directory: src/frontend
          wait-on: 'https://lhowsam.com'
