name: CI / Nightly unit tests
on: 
  schedule:
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: luke-h1/checkout@v2.3.4
    - name: Install modules
      run: npm i 

    - name: Run jest unit tests
      run: npx jest 

    - name: Start dev server  
      run: next dev -p 3000  

    - name: run UI tests 
      run: npm run cy:run 