name: CI / Nightly tests 
on: 
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: luke-h1/checkout@v2.3.4

    - name: Install dependencies
      run: npm ci 

    - name: build
      run: npm run build

    - name: UI tests 
      run: npm run cy:ci
