name: CI / Nightly tests 
on: 
  schedule:
    - cron: '0 22 * * *'
env:
  NEXT_PUBLIC_GRAPHCMS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_URL }}
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2
          
      - name: Install dependencies 
        run: npm ci

      - name: Jest 
        run: npm run test

      - name: Cypress run (local)
        uses: luke-h1/github-action@v2
        with:
          build: npm run build
          start: npm run start
          test: npm run cy:run
          wait-on: 'http://localhost:3000'
        env:
          NEXT_PUBLIC_GRAPHCMS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_URL }}

      - name: Cypress run (prod)
        uses: luke-h1/github-action@v2
        with:
          config: baseUrl=https://lhowsam.com
          test: npm run cy:prod
          wait-on: 'https://lhowsam.com'
