name: CI / Nightly tests 
on: 
  schedule:
    - cron: '0 22 * * *'
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies 
        run: yarn install --frozen-lockfile --check-files

      - name: Cypress run (local)
        uses: luke-h1/github-action@v2
        with:
          test: yarn workspace @lhowsam/frontend cy:run
          working-directory: src/frontend
          wait-on: 'http://localhost:3000'

      - name: Cypress run (prod)
        uses: luke-h1/github-action@v2
        with:
          test: yarn workspace @lhowsam/frontend cy:prod
          working-directory: src/frontend
          wait-on: 'https://lhowsam.com'
