name: Nightly unit tests
on: 
  schedule:
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: luke-h1/checkout@v2.3.4
    - name: Install modules
      run: npm i 
    - name: Run tests
      run: npx jest 