# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/cache
            ~/.dts/
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

        uses: volta-cli/action@v1
      - name: Use (Volta) Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v1.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm run build 
      - name: Run tests
        run: npm run test