name: CI /Node.js builds (push / pull)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2.3.4

      - name: Cache
        uses: luke-h1/cache@v2.1.3
        with:
          path: |
            ~/cache
            ~/.dts/
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Use (Volta) Node.js ${{ matrix.node-version }}
        uses: luke-h1/action@v1.6.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm i

      - name: build
        run: npm run build 
