name: CI / UI tests (production)
on:
  workflow_dispatch:
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies 
        run: npm ci

      - name: Cypress run (prod)
        uses: luke-h1/github-action@v2
        env: 
          NEXT_PUBLIC_GRAPHCMS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_URL }}
        with:
          build: npm run build
          start: npm run start
          test: npm run cy:prod
          wait-on: 'https://lhowsam.com'
