name: CI / UI tests (production)
on:
  workflow_dispatch:
env: 
  NEXT_PUBLIC_GRAPHCMS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_URL }}
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies 
        run: npm ci

      - name: Install dependencies 
        run: npm run cy:prod
