name: CI / UI tests (production)
on:
  workflow_dispatch:
env: 
  NEXT_PUBLIC_GRAPHCMS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_URL }}
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 14      

      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies 
        run: npm ci

      - name: Cypress run (prod)
        run: npm run cy-ci:prod