name: CI / UI tests (prod)
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 */12 * * *'
env: 
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  
jobs:
  test:
    name: e2e prod
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install moreutils
        run: sudo apt install moreutils            

      - name: setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: Install dependencies 
        run: pnpm i

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: prod UI tests
        run: pnpm run e2e:prod
        
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
