name: UI tests (prod)
on:
  workflow_dispatch:
  schedule: 
    - cron: '0 */12 * * *'
env: 
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  NODE_VERSION: 18.16.0
  PNPM_VERSION: 8.6.0

jobs:
  test:
    name: e2e prod
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: pnpm i --no-frozen-lockfile

      - name: Install Playwright Browsers
        run: ./node_modules/.bin/playwright install --with-deps chromium

      - name: prod UI tests
        run: pnpm run e2e:prod || exit 1
        
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report-prod-${{ github.event_name }}-${{ github.run_id }}
          path: playwright-report
