name: CI / UI tests (production)
on:
  workflow_dispatch:
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies 
        run: npm ci

      - name: Cypress run (prod)
        run: npm run cy:prod
