name: Stale PR check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: -1
          stale-pr-label: "PR stale"
          remove-stale-when-updated: true
