name: test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies 
        run: yarn install --frozen-lockfile --check-files
      
      - name: Cypress run
        uses: luke-h1/github-action@v2
        with:
          build: yarn workspace @lhowsam/frontend build
          start: yarn workspace @lhowsam/frontend start
          test: yarn workspace @lhowsam/frontend cy:run
          working-directory: src/frontend
          wait-on: 'http://localhost:3000'
