name: Unit Test 

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  unit_test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node Dependencies
        run: npm i --legacy-peer-deps
      - name: Run all Unit Tests
        run: npm run test