name: Unit tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        npm i --legacy-peer-deps     

    - name: npm run build 
      run: |
        npm run build 

    - name: run unit tests
      run: |
        npm run test
