name: Unit Test 

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  unit_test_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: 'setup node'
        uses: actions/setup-node@v1
        with:
         d  node-version: 14
      - name: Install Node Dependencies
        run: npm i --legacy-peer-deps
      - name: Run all Unit Tests
        run: npm run test